"use client";

import { useCallback, useEffect, useState } from "react";
import { useParams, usePathname, useRouter } from "next/navigation";
import { useChat } from "@ai-sdk/react";
import { DefaultChatTransport, type UIMessage } from "ai";
import { useQueryClient } from "@tanstack/react-query";
import { useGetConfig } from "@/hooks/data/useConfig/useConfig";
import { useGetSession } from "@/hooks/data/useChats/useChats";
import { notifyServerError } from "@/lib/server-error";
import { Navbar } from "./Navbar";
import { ChatSidebar } from "./ChatSidebar";
import { ChatMessageList } from "./ChatMessageList";
import { ChatInput } from "./ChatInput";

function toAssistantRole(role: string): "user" | "assistant" {
  if (role === "user") return "user";
  return "assistant";
}

function sessionIdFromParams(
  params: ReturnType<typeof useParams>,
): string | null {
  const raw = params?.sessionId;
  if (typeof raw === "string" && raw.length > 0) return raw;
  if (Array.isArray(raw) && raw[0]) return raw[0];
  return null;
}

export function ChatShell() {
  const router = useRouter();
  const pathname = usePathname();
  const params = useParams();
  const queryClient = useQueryClient();
  const { data: config } = useGetConfig();

  const routeSessionId = sessionIdFromParams(params);
  const isNewChatRoute = pathname === "/chat" || pathname === "/chat/";

  const [userSelectedModel, setUserSelectedModel] = useState<string | null>(
    null,
  );
  const [userSelectedReasoning, setUserSelectedReasoning] = useState<
    string | null
  >(null);
  const [streamSessionId, setStreamSessionId] = useState<string | null>(null);
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [hydratedSessionId, setHydratedSessionId] = useState<string | null>(
    null,
  );

  const activeSessionId = routeSessionId ?? streamSessionId;
  const activeModel =
    userSelectedModel || config?.defaultTextModel || "gemini-3.6-flash";
  const activeReasoning =
    userSelectedReasoning || config?.defaultReasoningLevel || "medium";

  const {
    data: sessionData,
    isLoading: isSessionLoading,
    isFetching: isSessionFetching,
  } = useGetSession(routeSessionId);

  const {
    messages: aiMessages,
    setMessages: setAiMessages,
    sendMessage,
    stop,
    status,
  } = useChat({
    transport: new DefaultChatTransport({
      api: "/api/chat",
    }),
    onData: (dataPart) => {
      if (dataPart.type !== "data-session") return;
      const data = dataPart.data as { sessionId?: string };
      const nextId = data?.sessionId;
      if (!nextId) return;

      setStreamSessionId(nextId);
      setHydratedSessionId(nextId);

      if (isNewChatRoute || routeSessionId !== nextId) {
        router.replace(`/chat/${nextId}`, { scroll: false });
      }
    },
    onFinish: () => {
      queryClient.invalidateQueries({ queryKey: ["chat-sessions"] });
      queryClient.invalidateQueries({ queryKey: ["profile"] });
      queryClient.invalidateQueries({ queryKey: ["chat-session"] });
    },
    onError: (err) => {
      notifyServerError(err, "Streaming error occurred");
    },
  });

  const isStreaming = status === "streaming" || status === "submitted";

  // Hydrate from session history when navigating between existing sessions
  useEffect(() => {
    if (isStreaming) return;

    if (!routeSessionId) {
      if (isNewChatRoute && !streamSessionId) {
        queueMicrotask(() => {
          setHydratedSessionId(null);
          setAiMessages([]);
        });
      }
      return;
    }

    if (sessionData && sessionData.id === routeSessionId) {
      if (hydratedSessionId !== routeSessionId) {
        // If this session was generated by the active stream, keep live aiMessages intact
        if (streamSessionId === routeSessionId) {
          queueMicrotask(() => {
            setHydratedSessionId(routeSessionId);
          });
          return;
        }

        const formatted: UIMessage[] = (sessionData.messages || []).map(
          (m, idx) => ({
            id: m.id || `hist-${idx}`,
            role: toAssistantRole(m.role),
            parts: [{ type: "text" as const, text: m.content }],
          }),
        );
        queueMicrotask(() => {
          setAiMessages(formatted);
          setHydratedSessionId(routeSessionId);
        });
      }
    }
  }, [
    routeSessionId,
    sessionData,
    setAiMessages,
    hydratedSessionId,
    isStreaming,
    isNewChatRoute,
    streamSessionId,
  ]);

  const handleSendMessage = useCallback(
    (text: string, model?: string, reasoning?: string) => {
      sendMessage(
        { text },
        {
          body: {
            model: model || activeModel,
            reasoning: reasoning || activeReasoning,
            sessionId: activeSessionId || undefined,
          },
        },
      );
    },
    [sendMessage, activeModel, activeReasoning, activeSessionId],
  );

  const handleNewChat = useCallback(() => {
    if (isStreaming) return;
    setStreamSessionId(null);
    setHydratedSessionId(null);
    setAiMessages([]);
    router.push("/chat");
  }, [router, setAiMessages, isStreaming]);

  const handleSelectSession = useCallback(
    (id: string) => {
      if (id === routeSessionId) return;
      if (isStreaming) return;
      setHydratedSessionId(null);
      setStreamSessionId(null);
      setAiMessages([]);
    },
    [routeSessionId, setAiMessages, isStreaming],
  );

  const streamingMessageId =
    isStreaming && aiMessages.length > 0
      ? aiMessages[aiMessages.length - 1]?.role === "assistant"
        ? aiMessages[aiMessages.length - 1].id
        : null
      : null;

  const showSessionLoading =
    Boolean(routeSessionId) &&
    !isStreaming &&
    streamSessionId !== routeSessionId &&
    hydratedSessionId !== routeSessionId &&
    (isSessionLoading ||
      isSessionFetching ||
      !sessionData ||
      sessionData.id !== routeSessionId);

  const showSuggestions =
    isNewChatRoute &&
    !streamSessionId &&
    aiMessages.length === 0 &&
    !isStreaming;

  return (
    <div className="bg-background font-body-md text-body-md text-on-surface flex h-dvh h-screen overflow-hidden">
      <ChatSidebar
        activeSessionId={activeSessionId}
        onSelectSession={handleSelectSession}
        onNewChat={handleNewChat}
        open={sidebarOpen}
        onOpenChange={setSidebarOpen}
      />

      <main className="bg-background relative flex h-dvh h-screen min-w-0 flex-1 flex-col">
        <Navbar onMenuClick={() => setSidebarOpen(true)} />

        <ChatMessageList
          messages={aiMessages}
          isStreaming={isStreaming}
          isSessionLoading={showSessionLoading}
          streamingMessageId={streamingMessageId}
        />

        <ChatInput
          onSend={handleSendMessage}
          onStop={stop}
          status={status}
          selectedModel={activeModel}
          onSelectModel={setUserSelectedModel}
          selectedReasoning={activeReasoning}
          onSelectReasoning={setUserSelectedReasoning}
          showSuggestions={showSuggestions}
        />
      </main>
    </div>
  );
}
